apiVersion: v1
kind: Pod
metadata:
  name: p1
  labels:
    for: me
spec:
  containers:
  - name: c1
    image: nginx
    livenessProbe:
      httpGet:
        path: /ibiwb
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5


