apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    for: initcont
spec:
  initContainers:
  - name: wait-for-svc
    image: busybox:1.28
    command: ['sh','-c','until nslookup myservice.default.svc.cluster.local;do echo waiting for service;sleep 2;done']
  containers:
  - name: mycont
    image: busybox:1.28
    command: ['sh','-c','echo app runs && sleep 3600']
    env:
    - name: MYNAME
      value: "Soham"
