apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels: 
    env: rc
spec:
  replicas: 3
  template:
    metadata:
      name: pod1
      labels:
        env: xyz
    spec:
      containers:
      - name: ngin-cont
        image: nginx
