apiVersion: v1
kind: Pod
metadata:
  labels:
    run: p1
  name: p123
spec:
  containers:
  - image: nginx
    name: p1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
status: {}
