apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: pod123
spec:
  containers:
  - image: nginx
    name: p1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "nm"
    operator: "Equal"
    value: "soham"
    effect: "NoSchedule"
status: {}
