apiVersion: v1
kind: Pod
metadata:
  labels:
    run: p1
  name: p1
spec:
  tolerations:
  - key: name
    operator: Equal
    value: abc
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: name
            operator: In
            values:
            - soham
  containers:
  - image: httpd
    name: p1
    resources: {}
